### PR TITLE
Use adb exec-out instead of shell

### PR DESCRIPTION
**Pull request by oblador**
This removes the need for the perl hack and makes it work with API level 25 which were producing corrupted images due to said hack.

### CODE REVIEW

**Review by skellock — APPROVED** [review]
Sweet!  Happy to see this go.  Cheers for the PR.

**Comment by oblador** [comment]
👍 LMK when you release this to NPM

**Comment by skellock** [comment]
She's up.

**Comment by oblador** [comment]
Beautiful 🙇

**Pull request merged**
